-- V1: Organizasyon semasi.
-- Birim, kurumdaki orgutsel birimi temsil eder. Kullanici tam olarak bir birime baglidir.
-- Sema elle yazilir; Hibernate ddl-auto=validate ile yalnizca dogrulama yapar (bkz. docs/decisions.md K-005).

CREATE TABLE birim (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod                 VARCHAR(20)  NOT NULL,
    ad                  VARCHAR(150) NOT NULL,
    olusturma_tarihi    TIMESTAMPTZ  NOT NULL,
    guncelleme_tarihi   TIMESTAMPTZ  NOT NULL,
    olusturan_kullanici VARCHAR(60)  NOT NULL,
    CONSTRAINT uq_birim_kod UNIQUE (kod)
);

COMMENT ON TABLE  birim IS 'Kurumsal orgutsel birim';
COMMENT ON COLUMN birim.kod IS 'Kisa birim kodu, ornek: BTGM';

CREATE TABLE kullanici (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullanici_adi       VARCHAR(60)  NOT NULL,
    ad_soyad            VARCHAR(150) NOT NULL,
    eposta              VARCHAR(180) NOT NULL,
    sifre_ozeti         VARCHAR(100) NOT NULL,
    rol                 VARCHAR(20)  NOT NULL,
    aktif               BOOLEAN      NOT NULL DEFAULT TRUE,
    birim_id            BIGINT       NOT NULL,
    olusturma_tarihi    TIMESTAMPTZ  NOT NULL,
    guncelleme_tarihi   TIMESTAMPTZ  NOT NULL,
    olusturan_kullanici VARCHAR(60)  NOT NULL,
    CONSTRAINT uq_kullanici_adi   UNIQUE (kullanici_adi),
    CONSTRAINT uq_kullanici_eposta UNIQUE (eposta),
    CONSTRAINT fk_kullanici_birim FOREIGN KEY (birim_id) REFERENCES birim (id),
    CONSTRAINT ck_kullanici_rol   CHECK (rol IN ('PERSONEL', 'AMIR', 'YONETICI'))
);

COMMENT ON COLUMN kullanici.sifre_ozeti IS 'BCrypt ozeti; duz metin sifre hicbir yerde tutulmaz';

-- Amir taleplerini birime gore listeler; bu indeks o sorgunun sik yolunu kisaltir.
CREATE INDEX ix_kullanici_birim ON kullanici (birim_id);
