-- V2: Is akisi semasi.
-- talep: is akisinin ana varligi. onay_kaydi: degistirilemez denetim izi.

CREATE TABLE talep (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baslik              VARCHAR(200) NOT NULL,
    aciklama            VARCHAR(4000) NOT NULL,
    tur                 VARCHAR(30)  NOT NULL,
    durum               VARCHAR(20)  NOT NULL,
    talep_eden_id       BIGINT       NOT NULL,
    birim_id            BIGINT       NOT NULL,
    olusturma_tarihi    TIMESTAMPTZ  NOT NULL,
    guncelleme_tarihi   TIMESTAMPTZ  NOT NULL,
    olusturan_kullanici VARCHAR(60)  NOT NULL,
    CONSTRAINT fk_talep_talep_eden FOREIGN KEY (talep_eden_id) REFERENCES kullanici (id),
    CONSTRAINT fk_talep_birim      FOREIGN KEY (birim_id)      REFERENCES birim (id),
    CONSTRAINT ck_talep_durum CHECK (durum IN ('TASLAK', 'BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI')),
    CONSTRAINT ck_talep_tur   CHECK (tur   IN ('IZIN', 'SATIN_ALMA', 'DONANIM', 'EGITIM', 'DIGER'))
);

COMMENT ON TABLE talep IS 'Personelin actigi talep; durum makinesi TASLAK -> BEKLEMEDE -> ONAYLANDI/REDDEDILDI';

-- Amir ekrani "bu birimin bekleyen talepleri" sorgusunu atar.
-- Bilesik indeksin kolon sirasi (durum, birim_id) secildi: durum kolonu her sorguda
-- esitlik ile filtreleniyor ve dagilimi dar (4 deger), birim_id ise ikincil daraltici.
CREATE INDEX ix_talep_durum_birim ON talep (durum, birim_id);

-- Personel ekrani "benim taleplerim" sorgusunu tarihe gore sirali atar.
CREATE INDEX ix_talep_talep_eden ON talep (talep_eden_id, olusturma_tarihi DESC);

CREATE TABLE onay_kaydi (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    talep_id            BIGINT       NOT NULL,
    onceki_durum        VARCHAR(20),
    yeni_durum          VARCHAR(20)  NOT NULL,
    islem_yapan_id      BIGINT       NOT NULL,
    aciklama            VARCHAR(1000),
    olusturma_tarihi    TIMESTAMPTZ  NOT NULL,
    guncelleme_tarihi   TIMESTAMPTZ  NOT NULL,
    olusturan_kullanici VARCHAR(60)  NOT NULL,
    CONSTRAINT fk_onay_kaydi_talep       FOREIGN KEY (talep_id)       REFERENCES talep (id),
    CONSTRAINT fk_onay_kaydi_islem_yapan FOREIGN KEY (islem_yapan_id) REFERENCES kullanici (id),
    CONSTRAINT ck_onay_kaydi_onceki CHECK (onceki_durum IS NULL OR onceki_durum IN ('TASLAK', 'BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI')),
    CONSTRAINT ck_onay_kaydi_yeni   CHECK (yeni_durum IN ('TASLAK', 'BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI'))
);

COMMENT ON TABLE onay_kaydi IS 'Denetim izi. Kayitlar guncellenmez ve silinmez, yalnizca eklenir.';

-- Talep detayinda gecmis kronolojik listelenir.
CREATE INDEX ix_onay_kaydi_talep ON onay_kaydi (talep_id, olusturma_tarihi);
