-- V3: Uygulama ici bildirim.
-- Talep durumu degistiginde ilgili kullaniciya okunmamis bir bildirim kaydi olusur.
-- E-posta veya SMS gonderimi kapsam disidir (bkz. docs/decisions.md Kapsam).

CREATE TABLE bildirim (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alici_id            BIGINT       NOT NULL,
    talep_id            BIGINT       NOT NULL,
    mesaj               VARCHAR(500) NOT NULL,
    okundu              BOOLEAN      NOT NULL DEFAULT FALSE,
    olusturma_tarihi    TIMESTAMPTZ  NOT NULL,
    guncelleme_tarihi   TIMESTAMPTZ  NOT NULL,
    olusturan_kullanici VARCHAR(60)  NOT NULL,
    CONSTRAINT fk_bildirim_alici FOREIGN KEY (alici_id) REFERENCES kullanici (id),
    CONSTRAINT fk_bildirim_talep FOREIGN KEY (talep_id) REFERENCES talep (id)
);

-- "Okunmamis bildirimlerim" sorgusu icin kismi indeks: yalnizca okunmamis satirlari kapsar,
-- boylece indeks zamanla buyumez.
CREATE INDEX ix_bildirim_alici_okunmamis ON bildirim (alici_id, olusturma_tarihi DESC) WHERE okundu = FALSE;
